name: Weekly Update Check

on:
  schedule:
    - cron: '0 1 * * 1'  # 每周一凌晨 1 点 UTC 时间

jobs:
  update-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run watcher script
      run: python watcher.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Auto update files on $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
      env:
        # 这里用GitHub自动提供的令牌，默认权限足够push当前仓库
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
